apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: Node-Port
  name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      service: Node-Port
  template:
    metadata:
      labels:
        service: Node-Port
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
